parser: babel-eslint
plugins:
  - babel
env:
  browser: true
  es6: true
  commonjs: true
  node: true
extends: eslint:recommended
parserOptions:
  sourceType: module
  ecmaFeatures:
    - impliedStrict
    - experimentalObjectRestSpread
globals:
  __webpack_public_path__: true
  __webpack_require__: true
  __projectRoot: true
  __codeRoot: true
  PrivilegeError: true
  ValidationError: true
  UserError: true
rules:
  babel/object-shorthand: 1
  indent:
    - 2
    - 2
  quotes:
    - 1
    - single
  semi:
    - 2
    - always
  comma-dangle:
    - 2
    - always-multiline
  no-unused-vars: 1
  no-console: 0
